theme:
  name: material
  logo: img/makie.svg
  features:
    # - announce.dismiss
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate # Table of contents is integrated on the left; does not appear separately on the right.
    - header.autohide # header disappears as you scroll
  palette:
    # Light mode / dark mode
    # We deliberately don't automatically use `media` to check a user's preferences. We default to light mode as
    # (a) it looks more professional, and (b) is more obvious about the fact that it offers a (dark mode) toggle.
    - scheme: default
      primary: white
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Lato
  icon:
    repo: fontawesome/brands/github # GitHub logo in top right
  #  logo: "material/circle-opacity" # Equinox logo in top left
  #  favicon: "_static/icon_transparent.svg"
  custom_dir: "_overrides" # Overriding part of the HTML

  # These additions are my own custom ones, having overridden a partial.
  twitter_name: "@lazarusAlon"
  twitter_url: "https://twitter.com/lazarusAlon"
  sponsor_name: "Sponsor"
  sponsor_url: "https://github.com/sponsors/lazarusA?o=esb"
site_name: Beautiful Makie
site_description: Makie Examples
site_author: Lazaro Alonso
site_url: ""

repo_url: https://github.com/MakieOrg/BeautifulMakie
repo_name: BeautifulMakie
edit_uri: "" # No edit button, as some of our pages are in /docs and some in /examples via symlink, so it's impossible for them all to be accurate

strict: true # Don't allow warnings during the build process
extra_javascript:
  # The below three make MathJax work, see https://squidfunk.github.io/mkdocs-material/reference/mathjax/
  - _static/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/custom.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - admonition
  - toc:
      permalink: "Â¤" # Adds a clickable permalink to each section heading
      toc_depth: 4
  - pymdownx.arithmatex: # Render LaTeX via MathJax
      generic: true
  - pymdownx.details # Allowing hidden expandable regions denoted by ???
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences # Seems to enable syntax highlighting when used with the Material theme.
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - md_in_html
plugins:
  - search # default search plugin; needs manually re-enabling when using any other plugins
  - autorefs # Cross-links to headings
  - include_exclude_files:
      exclude:
        - "_overrides"
#  - mknotebooks # Jupyter notebooks
  - mkdocs-video
nav:
  - "Home": "index.md"
  - "2D":
    - "Lines & Scatters":
      - "Lines":
          - "Single line": "examples/generated/2d/lines/line_single.md"
          - "Two lines": "examples/generated/2d/lines/line_two.md"
          - "Twin Axis": "examples/generated/2d/lines/line_twin_axis.md"
          - "Lines Colorbar": "examples/generated/2d/lines/line_cmap.md"
          - "Lines with different Colorbars": "examples/generated/2d/lines/line_cmaps.md"
          - "Lines with Colorbars around": "examples/generated/2d/lines/line_cmaps_a.md"
          - "Colored lines": "examples/generated/2d/lines/line_colored.md"
          - "Colored line Colorbar": "examples/generated/2d/lines/line_colored_cbar.md"
          - "Inset": "examples/generated/2d/lines/line_inset.md"
          - "Inset heatmap": "examples/generated/2d/lines/line_inset_h.md"
          - "Latex": "examples/generated/2d/lines/line_latex.md"
          - "Bessel 1st": "examples/generated/2d/lines/line_latex_bessel.md"
          - "Bessel 2nd": "examples/generated/2d/lines/line_latex_bessels.md"
          - "Time series": "examples/generated/2d/lines/line_time.md"
          - "x log ": "examples/generated/2d/lines/line_xlog.md"
          - "y log": "examples/generated/2d/lines/line_ylog.md"
          - "xy log": "examples/generated/2d/lines/line_xylog.md"
      - "Scatters":
          - "Scatter": "examples/generated/2d/scatters/scatter.md"
          - "Scatters with colormaps": "examples/generated/2d/scatters/scatters_colormap.md"
          - "Bubble plot": "examples/generated/2d/scatters/bubble_plot.md"
          - "Bubble plot logxy": "examples/generated/2d/scatters/bubble_plot_logxy.md"
          - "Iris dataset": "examples/generated/2d/scatters/iris_dataset.md"
          - "Makie Contributors": "examples/generated/2d/scatters/makie_contributors.md"

      - "Scatterslines":
          - "Sine": "examples/generated/2d/scatterlines/simple.md"
          - "Spirals ": "examples/generated/2d/scatterlines/spirals.md"
          - "Markers ": "examples/generated/2d/scatterlines/markers.md"
          - "Scatterlines and lines": "examples/generated/2d/scatterlines/scatterls_line.md"
          - "Scatterlines and lines: Legend out": "examples/generated/2d/scatterlines/scatterls_line_leg_out.md"

      - "Linesegments":
          - "linesegments": "examples/generated/2d/linesegments/linesegments.md"
          - "RRGraph": "examples/generated/2d/linesegments/RRGraph.md"

      - "Series":
          - "series": "examples/generated/2d/series/series.md"
      - "Stairs":
          - "stairs": "examples/generated/2d/stairs/stairs.md"
      - "Stem":
          - "stem": "examples/generated/2d/stem/stem.md"

      - "Contour":
          - "Egg shape": "examples/generated/2d/contour/egg_shape.md"
          - "Contour over heatmap": "examples/generated/2d/contour/contour_over_heatmap.md"
          - "Qubit": "examples/generated/2d/contour/qubit.md"
          - "Complex function": "examples/generated/2d/contour/complex_function.md"

      - "Arrows":
          - "arrows": "examples/generated/2d/arrows/arrows.md"
      - "Streamplot":
          - "Field lines: Electric charges": "examples/generated/2d/streamplot/streamplot.md"
          - "ode solution": "examples/generated/2d/streamplot/ode_solution.md"
          - "field heatmap": "examples/generated/2d/streamplot/field_heatmap.md"
          - "Poincare - Van der Paul": "examples/generated/2d/streamplot/poincare_vander.md"
          - "Complex Polya Field": "examples/generated/2d/streamplot/complex_polya_field.md"

    - "Statistics":
      - "Histogram":
          - "hist": "examples/generated/2d/histogram/hist.md"
          - "histograms on the sides": "examples/generated/2d/histogram/hists_on_the_sides.md"
          - "Bins and counts": "examples/generated/2d/histogram/bins_counts.md"
          - "Normalization options": "examples/generated/2d/histogram/normalizations.md"
          - "hist + pdf = density": "examples/generated/2d/histogram/hist_pdf.md"
          - "hist from image": "examples/generated/2d/histogram/parallel_image_hist.md"

      - "Density":
          - "Distributions": "examples/generated/2d/density/density.md"
          - "RDatasets: mtcars": "examples/generated/2d/density/mtcars_density.md"

      - "Boxplots":
          - "Boxplots collection": "examples/generated/2d/boxplots/boxplots_collection.md"
          - "Vertical / Horizontal": "examples/generated/2d/boxplots/vertical_horizontal.md"
          - "Boxes: airquality": "examples/generated/2d/boxplots/airquality.md"

      - "Violins":
          - "Single": "examples/generated/2d/violins/single.md"
          - "Violins collection": "examples/generated/2d/violins/collection_violins.md"
          - "Violins: airquality": "examples/generated/2d/violins/airquality.md"

      - "Errorbars":
          - "Simple x-y errorbars": "examples/generated/2d/errorbars/simple_x_y.md"
          - "y errorbar with colormap": "examples/generated/2d/errorbars/y_colormap.md"
          - "Errorbars formation": "examples/generated/2d/errorbars/errorbars.md"
      - "Barplots":
          - "Barplot & y errorbar": "examples/generated/2d/bars/barplot_y_error.md"
          - "x - Barplot error & y errorbar": "examples/generated/2d/bars/x_barplot_error_y_error.md"
          - "Barplot with colormap & y errorbar": "examples/generated/2d/bars/barplot_cmap_y_error.md"
          - "Stripped barplots": "examples/generated/2d/bars/stripped_bars.md"

    - "Heatmap":
          - "heatmap": "examples/generated/2d/heatmaps/heatmap.md"
          - "heatmap with text": "examples/generated/2d/heatmaps/text_heatmap.md"

    - "Filled curves":
          - "Bands: Intervals - Ribbon": "examples/generated/2d/band/band.md"
          - "Filled under line": "examples/generated/2d/band/filled_under.md"
          - "Filled under bell-shaped curves": "examples/generated/2d/band/filled_under_bell.md"
          - "Band - Ribbon - Between": "examples/generated/2d/band/band_ribbon.md"
          - "Confidence region": "examples/generated/2d/band/band_confidence_error.md"
    - "Polygons":
          - "Poygons: ngon": "examples/generated/2d/poly/poly_ngon.md"
  - "3D":
      - "Lines":
          - "Line 3d": "examples/generated/2d/lines3d/line3d.md"
          - "Lines, contour3d, contour, wireframe": "examples/generated/2d/lines3d/lines_wire_contour_3d.md"
          - "wireframe: torus": "examples/generated/2d/lines3d/wireframe_torus.md"
          - "Archimedean Spiral": "examples/generated/2d/lines3d/archimedean_spiral.md"

      - "Surfaces":
          - "surface": "examples/generated/2d/surfaces/surface.md"
          - "branching": "examples/generated/2d/surfaces/branching.md"
          - "constraints": "examples/generated/2d/surfaces/constraints.md"
          - "Gabriel's Horn": "examples/generated/2d/surfaces/gabriels_horn.md"
          - "Klein Bottle": "examples/generated/2d/surfaces/klein_bottle.md"
          - "One colour": "examples/generated/2d/surfaces/onecolor.md"
          - "Complex function": "examples/generated/2d/surfaces/complex_function.md"
          - "Revolution surface": "examples/generated/2d/surfaces/revolution_surface.md"
          - "Revolution surface s": "examples/generated/2d/surfaces/revolution_surface_s.md"
          - "Tesseral Spherical Harmonics": "examples/generated/2d/surfaces/tesseralSphericalH.md"
          - "Torus": "examples/generated/2d/surfaces/torus.md"
          - "Band 3D plane surface": "examples/generated/2d/surfaces/band3d.md"

      - "Meshscatters":
          - "Cube: meshscatters": "examples/generated/2d/mscatters/cube_mscatters.md"
          - "RGBA cube": "examples/generated/2d/mscatters/RGBAcube.md"
          - "Weighted random-geometric Graph 3D": "examples/generated/2d/mscatters/RRGraph3D.md"
          - "Screen-Space Ambient Occlusion, SSAO": "examples/generated/2d/mscatters/SSAO_meshscatter.md"
          - "SSAO: meshscatter grid": "examples/generated/2d/mscatters/SSAO_mgrid.md"
          - "Gauss-like shapes 2d": "examples/generated/2d/mscatters/gauss2d.md"

      - "Volumes":
          - "volume": "examples/generated/2d/volume/volume.md"
          - "volume contour & scatters": "examples/generated/2d/volume/volume_contour_scatters.md"
      - "Contour: volume-like, surface-like & 3d lines":
          - "contourf & contour3d": "examples/generated/2d/contour3d/contourf_contour3d.md"
          - "contour: volume-like": "examples/generated/2d/contour3d/contour_v.md"
      - "Meshes":
          - "Meshes: Cylinder, Pyramid, Sphere, Rect3": "examples/generated/2d/meshes/meshes.md"
          - "Earth and planes": "examples/generated/2d/meshes/Earth_planes.md"
          - "How to Cube": "examples/generated/2d/meshes/how_to_cube.md"
          - "Cube: Cyberpunk style": "examples/generated/2d/meshes/cpunkCube.md"
  - "Themes":
    - "Predefined":
          - "black: epicycloid": "examples/generated/2d/themes/black_epicycloid.md"
          - "dark: surface, contour3d & streamplot": "examples/generated/2d/themes/dark_surface_contour3d_streamplot.md"
          - "minimal: series": "examples/generated/2d/themes/minimal_series.md"
          - "ggplot2: stem": "examples/generated/2d/themes/ggplot2_stem.md"
          - "light: poly": "examples/generated/2d/themes/light_ngon.md"
          
  - "Animations":
    - "Basics":
          - "Scatter size": "examples/generated/2d/animations/scatter_size.md"

  - "Dashboards":
    - "Basics":
          - "Slider": "examples/generated/2d/dashboards/colorshemes.md"
          - "Menu and Sliders": "examples/generated/2d/dashboards/tesseral_spherical_harmonics.md"
          - "Material Capture: matcap": "examples/generated/2d/dashboards/matcap.md"

  - "Geo":
    - "Projections":
          - "Winkel Tripel, US States": "examples/generated/2d/geo/us_states.md"
          - "coastlines": "examples/generated/2d/geo/coastlines.md"
          - "projections": "examples/generated/2d/geo/projections.md"
          - "Submarine Cables": "examples/generated/2d/geo/submarine_cables.md"
          - "Blue Marble": "examples/generated/2d/geo/blue_marble.md"
          - "Moon": "examples/generated/2d/geo/moon.md"
          - "Donut: Earth & Sun": "examples/generated/2d/geo/donut_earth_sun.md"

  - "Ray tracing":
    - "Basics":
          - "Sphere and plane": "examples/generated/2d/rpr/sphere_plane.md"
  - "Data Visualization":
    - "Astronauts": "examples/generated/2d/datavis/astronauts.md"
    - "Earthquakes on Earth: depth not at scale": "examples/generated/2d/datavis/earthquakes.md"
    - "Leo's Syndrome": "examples/generated/2d/datavis/leos.md"
    - "Fractals": "examples/generated/2d/datavis/fractals.md"
    - "Eigenvalues: densities": "examples/generated/2d/datavis/eigenvals_densities.md"
    - "Eigenvalues evolution": "examples/generated/2d/datavis/eigenvalues_evolution.md"
    - "Strange attractors": "examples/generated/2d/datavis/strange_attractors.md"

  - "Algebra of Graphics":
    - "Statistics":
      - "Penguins, no AoG": "examples/generated/2d/aog/penguins.md"
 
